slogan: "Yarn (noun) 1. spun thread used for crochet 2. (informal) a long or rambling story"

theme: united
inverse: true

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    icon: "fa fa-user"

links:
  - title: "Instagram"
    url: http://www.instagram.com/jemgillam
    intro: "Jem's Instagram Profile"
    icon: "fa fa-instagram"
  - title: "Twitter"
    url: http://www.twitter.com/jemgillam
    intro: "Jem's Twitter Profile"
    icon: "fa fa-twitter"

widgets:
- search
- category
- recent_posts
- links
- tagcloud

rss:
fancybox: true
favicon: favicon.png
duoshuo_shortname:

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR

# share widgets
addthis: false
bdshare: false
jiathis: false
